%YAML:1.0
cam_width: 2208
cam_height: 1242

#cam L info ===========================
fx: 1065.35720614683
fy: 1065.6689380162
cx: 1133.61619952792
cy: 567.24023381768
k1: -0.103423450596362
k2: 0.123215002677024
k3: 9.46579504415051e-05
r1: -0.000613757818116764
r2: -0.0638339140907025
need_undistort: 1

#cam R info ===========================
#fx: 1065.07761408424
#fy: 1065.40569687692
#cx: 1071.45556203749
#cy: 675.787304360860
#k1: 0.0
#k2: 0.0
#k3: 0.0
#r1: 0.0
#r2: 0.0
#need_undistort: 0

#board info ===========================
board_width: 8  # Must be even
board_height: 5
gride_side_length: 0.1  #Grid side length (m)
board_order: 0 # 0 Represents that the grid in the upper right corner is black, otherwise white

#board segmentation params ===========================
noise_reflactivity_thd: 3
angle_thd: 0.5
board_edge_thd: 0.07
#some data path info
data_root_path: "../calib_data"
error_path_pnp: "/intermediate_results/L/pnp"
error_path_opt: "/intermediate_results/L/opt"
img_path: "/imgs/L"
cheesboard_path: "/board"
framesets_id_path: "/intermediate_results/frameID_list"
raw_pc_path: "/pc"
corner_detect_method: "opencv" # matlab or opencv

#22 26 48
#for black block extract
reflactivity_dec_step: 0.95
block_us_radius: 0.003 # for uniform sampling
black_pt_cluster_dst_thd: 0.0085

#for grid fitting optimization
#以下是 点云所在半径/网格边长的比率
uniform_sampling_radius: 0.0000
neighbour_radius_rate: 0.8
cost_radius_rate: 0.35
#  The cost_radius_rate generally not greater than neighbour_radius_rate / √2， otherwise cost_radius_rate*√2 > neighbour_radius_rate,
#  The search point for gradient will exceed the range of current field points, resulting in instability
max_iter_time: 20

#for final calibration
use_pnp_init: 1

#debug params
apply_noise_test: 0
noise_x: 0.01
noise_y: 0.01
noise_yaml: 0.00
DEBUG_SHOW: 0

debug_param: 1
display_remove_oclusion: 0



